[basic]
log = "debug"

[web]
address = "127.0.0.1"
port = 18081
static_dir = "./html/"

# username:password[cipher],username:password,......
cipher = "sha256" # cipher method
auth = "meteorcat:fe67eaa1f8b3b85a3a135795128abf9f4594f95128bef04c276f7dbcf1198b78"

#[redis]
## redis://username:password@localhost:6379/1
#url = "redis://username:password@localhost:6379/1"
#prefix = "systemstat_"

#[db]
## mysql://username:password@localhost:3306/database
#url = "mysql://root:root@localhost/systemstat"


[tcp]
#todo: tcp transmission


[udp]
#todo: udp transmission

[websocket]
# todo: websocket transmission





